spring:
  config:
    activate:
      on-profile: "k8s-grpc"

grpc:
  server:
    port: ${GRPC_PORT:9090}
    discovery:
      service-name: ${spring.application.name}

  client:
    tenant-service:
      name: tenant-service
      negotiationType: plaintext
      enable-keep-alive: true
      address: dns:///tenant-service:50007
      discovery:
        enabled: false
    pass-service:
      name: pass-service
      negotiationType: plaintext
      enable-keep-alive: true
      address: dns:///pass-service:50003
      discovery:
        enabled: false

  reflection:
    enable: true