spring:
  config:
    activate:
      on-profile: actuator

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges, busrefresh, info, metrics, prometheus
