spring:
  config:
    activate:
      on-profile: "k8s-routes"
  cloud:
    gateway:
      routes:
        - id: admin-service-admins
          uri: http://admin-service:60002
          predicates:
            - Path=/admins/**

        - id: admin-service-auth
          uri: http://admin-service:60002
          predicates:
            - Path=/auth/**

        - id: hospital-service
          uri: http://hospital-service:60004
          predicates:
            - Path=/hospitals/**
            - Platform=ADMIN

        - id: patient-service
          uri: http://patient-service:60006
          predicates:
            - Path=/patients/**
            - Platform=ADMIN

        - id: pass-service
          uri: http://pass-service:60003
          predicates:
            - Path=/passes/**
            - Platform=ADMIN

        - id: log-service
          uri: http://log-service:60010
          predicates:
            - Path=/pass-logs/**
            - Platform=ADMIN

        # Swagger UI routes

        - id: swagger-admin
          uri: http://admin-service:60002
          predicates:
            - Path=/v3/api-docs/admin
          filters:
            - RewritePath=/v3/api-docs/admin, /v3/api-docs

        - id: swagger-pass
          uri: http://pass-service:60003
          predicates:
            - Path=/v3/api-docs/pass
          filters:
            - RewritePath=/v3/api-docs/pass, /v3/api-docs

        - id: swagger-hospital
          uri: http://hospital-service:60004
          predicates:
            - Path=/v3/api-docs/hospital
          filters:
            - RewritePath=/v3/api-docs/hospital, /v3/api-docs

        - id: swagger-patient
          uri: http://patient-service:60006
          predicates:
            - Path=/v3/api-docs/patient
          filters:
            - RewritePath=/v3/api-docs/patient, /v3/api-docs

        - id: swagger-log
          uri: http://log-service:60010
          predicates:
            - Path=/v3/api-docs/log
          filters:
            - RewritePath=/v3/api-docs/log, /v3/api-docs




