spring:
  config:
    activate:
      on-profile: "swagger"

springdoc:
  swagger-ui:
    urls:
      - name: admin
        url: /v3/api-docs/admin
      - name: hospital
        url: /v3/api-docs/hospital
      - name: patient
        url: /v3/api-docs/patient
      - name: pass
        url: /v3/api-docs/pass
      - name: log
        url: /v3/api-docs/log

        
