spring:
  config:
    activate:
      on-profile: "k8s-grpc"

grpc:
  server:
    port: ${GRPC_PORT:50003}
    discovery:
      service-name: ${spring.application.name}
  client:
    hospital-service:
      name: hospital-service
      negotiationType: plaintext
      enable-keep-alive: true
      address: dns:///hospital-service:50004  # dns:/// 프리픽스 꼭 붙이기!
      discovery:
        enabled: false
    member-service:
      name: member-service
      negotiationType: plaintext
      enable-keep-alive: true
      address: dns:///member-service:50001
      discovery:
        enabled: false
    patient-service:
      name: patient-service
      negotiationType: plaintext
      enable-keep-alive: true
      address: dns:///patient-service:50006
      discovery:
        enabled: false
    log-service:
      name: log-service
      negotiationType: plaintext
      enable-keep-alive: true
      address: dns:///log-service:50010
      discovery:
        enabled: false
    did-agent:
      name: did-agent
      negotiationType: plaintext
      enable-keep-alive: true
      address: dns:///did-agent:50005
      discovery:
        enabled: false

  reflection:
    enable: true
